apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: f5tts-model-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-k8s-general
  resources:
    requests:
      storage: 10Gi
